
# This file is automatically generated, you probably don't want to edit this

PTMOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "PTMOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            factor1 = NULL,
            factor2 = NULL,
            block = NULL,
            nest_id = NULL,
            design = "crd",
            subplot = "subplot.eq.1",
            model = "lm",
            family = "norm",
            trtvsctrl = FALSE,
            simple = TRUE,
            adjust = "default",
            pal = "pal_okabe_ito",
            tech_reps = FALSE,
            join_blocks = FALSE,
            y_label = NULL, ...) {

            super$initialize(
                package="PTM",
                name="PTM",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..factor1 <- jmvcore::OptionVariable$new(
                "factor1",
                factor1)
            private$..factor2 <- jmvcore::OptionVariable$new(
                "factor2",
                factor2)
            private$..block <- jmvcore::OptionVariable$new(
                "block",
                block)
            private$..nest_id <- jmvcore::OptionVariable$new(
                "nest_id",
                nest_id)
            private$..design <- jmvcore::OptionList$new(
                "design",
                design,
                options=list(
                    "crd",
                    "crds",
                    "rcbd",
                    "rcbds",
                    "grcbd",
                    "grcbds",
                    "spd",
                    "gspd"),
                default="crd")
            private$..subplot <- jmvcore::OptionList$new(
                "subplot",
                subplot,
                options=list(
                    "subplot.eq.1",
                    "subplot.eq.2"),
                default="subplot.eq.1")
            private$..model <- jmvcore::OptionList$new(
                "model",
                model,
                options=list(
                    "lm",
                    "lmer",
                    "aov_4",
                    "glm",
                    "glmer"),
                default="lm")
            private$..family <- jmvcore::OptionList$new(
                "family",
                family,
                options=list(
                    "norm",
                    "binom",
                    "negbin",
                    "gamma"),
                default="norm")
            private$..trtvsctrl <- jmvcore::OptionBool$new(
                "trtvsctrl",
                trtvsctrl,
                default=FALSE)
            private$..simple <- jmvcore::OptionBool$new(
                "simple",
                simple,
                default=TRUE)
            private$..adjust <- jmvcore::OptionList$new(
                "adjust",
                adjust,
                options=list(
                    "default",
                    "none",
                    "holm",
                    "fdr"),
                default="default")
            private$..pal <- jmvcore::OptionList$new(
                "pal",
                pal,
                options=list(
                    "pal_ggplot",
                    "pal_okabe_ito",
                    "pal_okabe_ito_blue",
                    "pal_npg",
                    "pal_aaas",
                    "pal_jco",
                    "pal_frontiers"),
                default="pal_okabe_ito")
            private$..tech_reps <- jmvcore::OptionBool$new(
                "tech_reps",
                tech_reps,
                default=FALSE)
            private$..join_blocks <- jmvcore::OptionBool$new(
                "join_blocks",
                join_blocks,
                default=FALSE)
            private$..y_label <- jmvcore::OptionString$new(
                "y_label",
                y_label)

            self$.addOption(private$..dep)
            self$.addOption(private$..factor1)
            self$.addOption(private$..factor2)
            self$.addOption(private$..block)
            self$.addOption(private$..nest_id)
            self$.addOption(private$..design)
            self$.addOption(private$..subplot)
            self$.addOption(private$..model)
            self$.addOption(private$..family)
            self$.addOption(private$..trtvsctrl)
            self$.addOption(private$..simple)
            self$.addOption(private$..adjust)
            self$.addOption(private$..pal)
            self$.addOption(private$..tech_reps)
            self$.addOption(private$..join_blocks)
            self$.addOption(private$..y_label)
        }),
    active = list(
        dep = function() private$..dep$value,
        factor1 = function() private$..factor1$value,
        factor2 = function() private$..factor2$value,
        block = function() private$..block$value,
        nest_id = function() private$..nest_id$value,
        design = function() private$..design$value,
        subplot = function() private$..subplot$value,
        model = function() private$..model$value,
        family = function() private$..family$value,
        trtvsctrl = function() private$..trtvsctrl$value,
        simple = function() private$..simple$value,
        adjust = function() private$..adjust$value,
        pal = function() private$..pal$value,
        tech_reps = function() private$..tech_reps$value,
        join_blocks = function() private$..join_blocks$value,
        y_label = function() private$..y_label$value),
    private = list(
        ..dep = NA,
        ..factor1 = NA,
        ..factor2 = NA,
        ..block = NA,
        ..nest_id = NA,
        ..design = NA,
        ..subplot = NA,
        ..model = NA,
        ..family = NA,
        ..trtvsctrl = NA,
        ..simple = NA,
        ..adjust = NA,
        ..pal = NA,
        ..tech_reps = NA,
        ..join_blocks = NA,
        ..y_label = NA)
)

PTMResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "PTMResults",
    inherit = jmvcore::Group,
    active = list(
        model_builder_notes = function() private$.items[["model_builder_notes"]],
        plot = function() private$.items[["plot"]],
        plot_notes = function() private$.items[["plot_notes"]],
        model = function() private$.items[["model"]],
        model_notes = function() private$.items[["model_notes"]],
        coef = function() private$.items[["coef"]],
        emm = function() private$.items[["emm"]],
        contrasts = function() private$.items[["contrasts"]],
        check = function() private$.items[["check"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Plot The Model")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="model_builder_notes",
                title="Model Builder Notes"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Plot the Model",
                width=400,
                height=300,
                renderFun=".plot"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="plot_notes",
                title="Plot Notes"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="model",
                title="Model"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="model_notes",
                title="Model Notes"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="coef",
                title="Model coefficients"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="emm",
                title="Estimated Model Means"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="contrasts",
                title="Model Contrasts"))
            self$add(jmvcore::Image$new(
                options=options,
                name="check",
                title="Check the Model",
                width=500,
                height=300,
                renderFun=".plot_check"))}))

PTMBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "PTMBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "PTM",
                name = "PTM",
                version = c(1,0,0),
                options = options,
                results = PTMResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Plot The Model
#'
#' 
#' @param data .
#' @param dep .
#' @param factor1 .
#' @param factor2 .
#' @param block .
#' @param nest_id .
#' @param design .
#' @param subplot .
#' @param model .
#' @param family .
#' @param trtvsctrl .
#' @param simple .
#' @param adjust .
#' @param pal .
#' @param tech_reps .
#' @param join_blocks .
#' @param y_label .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$model_builder_notes} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot_notes} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$model} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$model_notes} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$coef} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$emm} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$contrasts} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$check} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
PTM <- function(
    data,
    dep,
    factor1,
    factor2,
    block,
    nest_id,
    design = "crd",
    subplot = "subplot.eq.1",
    model = "lm",
    family = "norm",
    trtvsctrl = FALSE,
    simple = TRUE,
    adjust = "default",
    pal = "pal_okabe_ito",
    tech_reps = FALSE,
    join_blocks = FALSE,
    y_label) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("PTM requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(factor1)) factor1 <- jmvcore::resolveQuo(jmvcore::enquo(factor1))
    if ( ! missing(factor2)) factor2 <- jmvcore::resolveQuo(jmvcore::enquo(factor2))
    if ( ! missing(block)) block <- jmvcore::resolveQuo(jmvcore::enquo(block))
    if ( ! missing(nest_id)) nest_id <- jmvcore::resolveQuo(jmvcore::enquo(nest_id))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(factor1), factor1, NULL),
            `if`( ! missing(factor2), factor2, NULL),
            `if`( ! missing(block), block, NULL),
            `if`( ! missing(nest_id), nest_id, NULL))


    options <- PTMOptions$new(
        dep = dep,
        factor1 = factor1,
        factor2 = factor2,
        block = block,
        nest_id = nest_id,
        design = design,
        subplot = subplot,
        model = model,
        family = family,
        trtvsctrl = trtvsctrl,
        simple = simple,
        adjust = adjust,
        pal = pal,
        tech_reps = tech_reps,
        join_blocks = join_blocks,
        y_label = y_label)

    analysis <- PTMClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

